const products = [
  {
    _id: '1',
    name: 'Product 1',
    image: '/images/Coming-Soon.jpeg',
    description: 'Description for product 1',
    brand: 'The Kellen Collection',
    category: 'Clothing',
    price: 25.99,
    shippingCost: 'Free Shipping',
    countInStock: 4,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '2',
    name: 'Product 2',
    image: '/images/Coming-Soon.jpeg',
    description: 'Description for product 2',
    brand: 'The Kellen Collection',
    category: 'Clothing',
    price: 25.99,
    shippingCost: 'Free Shipping',
    countInStock: 40,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '3',
    name: 'Product 3',
    image: '/images/Coming-Soon.jpeg',
    description: 'Description for product 3',
    brand: 'The Kellen Collection',
    category: 'Clothing',
    price: 25.99,
    shippingCost: 'Free Shipping',
    countInStock: 40,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '4',
    name: 'Product 4',
    image: '/images/Coming-Soon.jpeg',
    description: 'Description for product 4',
    brand: 'The Kellen Collection',
    category: 'Clothing',
    price: 25.99,
    shippingCost: 'Free Shipping',
    countInStock: 40,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '5',
    name: 'Product 5',
    image: '/images/Coming-Soon.jpeg',
    description: 'Description for product 5',
    brand: 'The Kellen Collection',
    category: 'Clothing',
    price: 25.99,
    shippingCost: 'Free Shipping',
    countInStock: 40,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Product 6',
    image: '/images/Coming-Soon.jpeg',
    description: 'Description for product 6',
    brand: 'The Kellen Collection',
    category: 'Clothing',
    price: 25.99,
    shippingCost: 'Free Shipping',
    countInStock: 40,
    rating: 3.5,
    numReviews: 10,
  },
]

export default products;